### ISSUE TITLE
Could not find com.github.shaoshuai904:RecordWav:1.0.2.

### ISSUE THREAD

**Issue by lizhongyuan3** [shaoshuai904/shaoshuai904#1]
Could not find com.github.shaoshuai904:RecordWav:1.0.2.

**Comment by shaoshuai904** [comment]
RecordWav:1.0.2 是有的，（虽然最新版本是1.2.1）
你看下你项目里build.gradle文件中有没有配置
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
看异常信息是类库加载失败了。

同时，你可以尝试在本地运行：./gradlew :app:dependencies
查看项目中 lib 引用关系，查找 RecordWav 的上层引用库，进行版本升级。
或添加配置：implementation 'com.github.shaoshuai904:RecordWav:1.2.1'
新版本会覆盖旧版本。

**Comment by lizhongyuan3** [comment]
![image](https://user-images.githubusercontent.com/44236581/183798647-ccf587ae-2c53-4ec2-83b1-70299329ff70.png)

**Comment by lizhongyuan3** [comment]
![image](https://user-images.githubusercontent.com/44236581/183798810-c4762736-9b57-4ec5-9105-b8bb7679d58a.png)
![image](https://user-images.githubusercontent.com/44236581/183798831-1c013ea1-f6ee-4ea1-8482-e064c51d5133.png)
直接引用的 无上层引用 无法加载

**Comment by lizhongyuan3** [comment]
在 jitpack 里各个版本都是可以找到的，就是项目 gradle 无法加载，这个项目是我直接加载测试用的

**Comment by shaoshuai904** [comment]
额，这个就需要看下你本地的gradle 版本和配置了，问题很奇怪 仓库是一个，你能加载到1.0.3  缺不能加载其他版本...

**Comment by lizhongyuan3** [comment]
嗯嗯 我同事也是 😂

**Comment by shaoshuai904** [comment]
额，你同事遇到跟你同样的 不能加载指定版本问题么，
能告知一下 你本地 gradle 版本 和 项目 target sdk 等配置么

**Comment by lizhongyuan3** [comment]
gradle 7.0.3

**Comment by lizhongyuan3** [comment]
gradle 7.0.4 Android sdk 31
